server:
  host: "0.0.0.0"
  http_port: 3001
  ws_port: 8081

influxdb:
  url: "http://127.0.0.1:8086"
  token: "my-super-secret-token"
  org: "myorg"
  buckets:
    candles: "trading_candles"
    orderbook: "trading_orderbook"
    orderbook_agg: "trading_orderbook_agg"
